var Courses={
  data:[{id:1,cat:'va',title:'Virtual Assistant Mastery',provider:'OnlineJobs.ph Academy',duration:'Self-paced',icon:'ðŸ’¼',url:'https://www.onlinejobs.ph/',desc:'Learn the skills to land your first VA client.'},{id:2,cat:'bpo',title:'Customer Service Fundamentals',provider:'Google (via Coursera)',duration:'8 hours',icon:'ðŸŽ§',url:'https://grow.google/certificates/',desc:'Google-backed certification for customer service.'},{id:3,cat:'tech',title:'Python for Beginners',provider:'freeCodeCamp',duration:'Free',icon:'ðŸ',url:'https://www.freecodecamp.org/',desc:'Learn Python from scratch with projects.'},{id:4,cat:'marketing',title:'Social Media Marketing',provider:'Meta Blueprint',duration:'4 hours',icon:'ðŸ“±',url:'https://www.facebook.com/business/learn',desc:'Free Meta certification for social media.'},{id:5,cat:'data',title:'Excel for Data Entry',provider:'Microsoft Learn',duration:'3 hours',icon:'ðŸ“Š',url:'https://learn.microsoft.com/',desc:'Master Excel for data entry roles.'},{id:6,cat:'va',title:'Canva Design for VAs',provider:'Canva Design School',duration:'2 hours',icon:'ðŸŽ¨',url:'https://www.canva.com/designschool/',desc:'Create graphics using Canva.'},{id:7,cat:'bpo',title:'BPO Interview Prep',provider:'JobStreet PH',duration:'1 hour',icon:'ðŸŽ¯',url:'https://www.jobstreet.com.ph/',desc:'Ace your BPO interview.'},{id:8,cat:'tech',title:'Web Development Basics',provider:'freeCodeCamp',duration:'300 hours',icon:'ðŸ’»',url:'https://www.freecodecamp.org/',desc:'HTML, CSS, JavaScript foundation.'},{id:9,cat:'marketing',title:'Digital Marketing Certificate',provider:'Google Digital Garage',duration:'40 hours',icon:'ðŸŒ',url:'https://learndigital.withgoogle.com/',desc:'Free Google certification in marketing.'},{id:10,cat:'data',title:'Data Entry Professional',provider:'Alison',duration:'3 hours',icon:'âŒ¨ï¸',url:'https://alison.com/',desc:'Professional data entry skills.'},{id:11,cat:'va',title:'Email Management',provider:'Udemy Free',duration:'2 hours',icon:'ðŸ“§',url:'https://www.udemy.com/',desc:'Manage client inboxes professionally.'},{id:12,cat:'tech',title:'ChatGPT & AI Productivity',provider:'Google (via Coursera)',duration:'5 hours',icon:'ðŸ¤–',url:'https://grow.google/',desc:'Use AI to supercharge your workflow.'}],
  filter:'all', inited:false,
  init:function(){
    if(Courses.inited) return; Courses.inited=true;
    var pills=['All Courses','Virtual Assistant','BPO / CSR','Tech / IT','Marketing','Data Entry'];
    var cats=['all','va','bpo','tech','marketing','data'];
    App.$('courses-pills').innerHTML=cats.map(function(c,i){ return '<button class="cat-pill'+(i===0?' active':'')+'" data-cat="'+c+'" onclick="Courses.filter(\''+c+'\',this)">'+pills[i]+'</button>'; }).join('');
    Courses.render('all');
  },
  render:function(cat){ Courses.filter=cat; var f=cat==='all'?Courses.data:Courses.data.filter(function(c){return c.cat===cat;}), con=App.$('courses-grid'); if(!con)return; con.innerHTML=f.length?f.map(function(c){return '<div class="course-card"><div class="course-icon">'+c.icon+'</div><div><div class="course-title">'+App.esc(c.title)+'</div><div class="course-provider">'+App.esc(c.provider)+'</div></div><div class="course-desc">'+App.esc(c.desc)+'</div><div class="course-footer"><span class="course-duration">â± '+App.esc(c.duration)+'</span><a href="'+App.esc(c.url)+'" target="_blank" class="enroll-btn">Enroll Free â†—</a></div></div>';}).join(''):'<div class="empty"><h3>No courses in this category</h3></div>'; },
  filter:function(cat,btn){ document.querySelectorAll('.cat-pill').forEach(function(p){p.classList.remove('active');}); btn.classList.add('active'); Courses.render(cat); }
};

