with open('index.html', 'r', encoding='utf-8') as f:
    h = f.read()

# EMPLOYER FAQ
h = h.replace('<span>Is it free to post a job?</span>', '<span>How does RankFixer differ from a traditional staffing agency?</span>')
h = h.replace('Yes, posting a job is free to start. Create an employer account, fill in the details, and your listing goes live to thousands of active job seekers in the Philippines immediately.', 'RankFixer operates as a managed workforce partner, not a placement agency. We handle infrastructure, onboarding, communication standards, and ongoing operational oversight — so you get a functioning remote team, not just a hire.')
h = h.replace('<span>What information do I need to post a job?</span>', '<span>What does a managed remote team engagement look like?</span>')
h = h.replace("You'll need a job title, company name, work setup (on-site, remote, or hybrid), employment type, and a job description. Salary range and an external application URL are optional but recommended.", 'Engagements begin with a role scoping call, followed by candidate shortlisting from our vetted pool. Selected candidates complete structured onboarding before going live. Ongoing support includes performance check-ins and operational adjustments.')
h = h.replace('<span>Can I edit or remove a job posting after publishing?</span>', '<span>Can I post a role directly through the platform?</span>')
h = h.replace('Yes. Manage all your active listings from the Your Postings section in your employer dashboard. You can update details or delete a listing once the position has been filled.', 'Yes. Employer accounts can post roles directly through the dashboard. Postings go live to our active candidate network immediately and can be edited or removed at any time from your employer dashboard.')
h = h.replace('<span>What types of candidates will I reach?</span>', '<span>What types of employers does RankFixer work with?</span>')
h = h.replace('Job Copilot PH focuses on the Philippine talent market — BPO, customer service, tech, virtual assistant, and administrative roles. A significant share of candidates are actively seeking remote and WFH opportunities.', 'RankFixer works with SMEs, agency operators, and growth-stage companies that need structured remote operational capacity — particularly in client services, marketing operations, administrative support, and AI-assisted workflows.')
h = h.replace('<span>How do applicants apply through my listing?</span>', '<span>What makes Philippine operational talent a strong fit?</span>')
h = h.replace('Each listing has a unique shareable URL. If you provide an external application link, candidates are redirected there to complete their application — keeping you in full control of the hiring process.', 'Philippine professionals bring strong English proficiency, cultural alignment with Western work norms, and high adaptability to async workflows. Combined with the RankFixer infrastructure layer, you get reliable, scalable operational capacity.')

# ACCOUNT FAQ
h = h.replace('<span>How do I create an account?</span>', '<span>How do I join the RankFixer talent network?</span>')
h = h.replace("Click Sign Up at the top of the page, choose Job Seeker or Employer / Recruiter, then enter your name, email, and password. It's free and takes under a minute.", 'Click Join Network at the top of the page, select your role (Candidate or Employer), and complete your profile. Candidates with complete profiles are prioritized in our active matching pool.')
h = h.replace('<span>How do I set up my job seeker profile?</span>', '<span>How do I build a strong candidate profile?</span>')
h = h.replace('After signing in go to My Profile. You can add your professional identity, bio, skills with proficiency ratings, work experience, education, and upload your resume as a PDF. A complete profile helps employers find and evaluate you faster.', 'Go to My Profile and fill in your professional identity, target discipline, skills with proficiency ratings, work experience, and education. Upload your resume as a PDF. A complete profile surfaces you to relevant employer-clients in our network.')
h = h.replace('<span>Can employers see my profile publicly?</span>', '<span>Can employer-clients view my profile directly?</span>')
h = h.replace('Yes — your profile has a public URL where employers can view your bio, skills, experience, education, and download your uploaded resume PDF. Changes you save appear on your public profile immediately.', 'Yes — your profile has a shareable public URL that employer-clients can access to review your skills, experience, and resume. Updates you save are reflected on your public profile immediately.')
h = h.replace('<span>What work setup preferences can I set?</span>', '<span>What availability options can I set?</span>')
h = h.replace('You can set your availability to Full Remote (Home-based), Hybrid, or On-site Only. This lets employers immediately see what arrangement you are open to, improving your match quality.', 'You can set your availability to Full Remote, Hybrid, or On-site. This signals your operational fit to employer-clients and improves how you are matched to live role requirements in the network.')

# JOB SEEKERS FAQ
h = h.replace('<span>Is it free to search and apply for jobs?</span>', '<span>What is the RankFixer seat facility?</span>')
h = h.replace('Yes — browsing listings and applying is completely free for job seekers. No hidden fees, no subscriptions, and no pay-to-apply gates. Just create a free account and start applying.', 'The RankFixer facility operates a 200-seat managed workspace in Bislig City, providing employer-clients with structured, infrastructure-ready remote teams. All candidates in our network are vetted and operationally prepared.')
h = h.replace('<span>What types of jobs are available?</span>', '<span>What operational roles does RankFixer fill?</span>')
h = h.replace('Job Copilot PH lists over 3,500 verified openings across BPO / Customer Service, Virtual Assistant, Remote / Work-from-Home, Social Media Management, Software Development, and Data Entry. New listings are added every day.', 'RankFixer fills roles across Remote Operations, Client Support, Executive Assistance, AI-Native Workflows, Marketing Operations, and Administrative Support. All roles are tied to live demand signals from our operational intelligence system.')
h = h.replace('<span>How do I apply for a job?</span>', '<span>How does AI-assisted workflow onboarding work?</span>')
h = h.replace('Click any listing to view its full details, then hit Apply. If the employer provided an external application URL you will be redirected there. Keeping your profile and resume up to date helps employers review you faster.', 'Candidates selected for AI-assisted workflow roles undergo structured onboarding covering tool stack orientation, async communication protocols, and documentation standards. This ensures consistent output quality from day one.')
h = h.replace('<span>Can I filter for remote / work-from-home jobs only?</span>', '<span>What communication standards are required?</span>')
h = h.replace('Yes. Use the Remote only toggle on the Browse Jobs page to instantly filter to WFH positions. You can also narrow results by job category, employment type, and salary range.', 'RankFixer-managed teams operate on structured async communication standards: documented task handoffs, daily written status logs, and defined escalation paths. Real-time availability windows are coordinated per client timezone.')
h = h.replace('<span>What is the Application Tracker?</span>', '<span>What infrastructure does the facility provide?</span>')
h = h.replace('The Application Tracker lets you log and monitor every job you have applied to in one place — statuses, dates, notes — so you stay organised throughout your job search.', 'The Bislig City facility provides redundant internet connections, backup power, managed workstations, and IT support. Employers get infrastructure certainty without managing it themselves.')
h = h.replace('<span>How do I save jobs to review later?</span>', '<span>How does workforce intelligence work?</span>')
h = h.replace('Click the bookmark icon on any listing while browsing. All saved jobs appear under the Saved tab in your account. You need to be signed in for this feature to work.', 'Our operational intelligence system tracks live role demand, candidate readiness signals, and placement velocity. This data informs how we source, screen, and match candidates to employer needs — reducing time-to-productivity significantly.')

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(h)
print('All FAQ sections updated.')
